[Service]
  Port = 49999
  Timeout = 5000
  ConnectRetries = 10
  Labels = [ 'Template' ]
  StartupMsg = 'Template device started'
  CheckInterval = '10s'

[Clients]
  [Clients.Data]
    Host = 'localhost'
    Port = 48080

  [Clients.Metadata]
    Host = 'localhost'
    Port = 48081

[Device]
  DataTransform = true
  InitCmd = ''
  InitCmdArgs = ''
  MaxCmdOps = 128
  MaxCmdResultLen = 256
  RemoveCmd = ''
  RemoveCmdArgs = ''
  ProfilesDir = ''
  SendReadingsOnChanged = true
  [Device.Discovery]
    Enabled = true
    Interval = 10

[Logging]
  LogLevel = 'DEBUG'

[Driver]
  TestParam1 = 'Hello'
  TestParam2 = 'World'

