[Service]
  Port = 49990
  Timeout = 5000
  ConnectRetries = 3
  Labels = [ "Template" ]
  StartupMsg = "Example template device started"
  ReadMaxLimit = 256
  CheckInterval = "10s"

[Clients]
  [Clients.Data]
    Host = "localhost"
    Port = 48080

  [Clients.Metadata]
    Host = "localhost"
    Port = 48081

[Device]
  DataTransform = true
  Discovery = false
  InitCmd = ""
  InitCmdArgs = ""
  MaxCmdOps = 128
  MaxCmdResultLen = 256
  RemoveCmd = ""
  RemoveCmdArgs = ""
  ProfilesDir = ""
  SendReadingsOnChanged = true

[Logging]
  RemoteURL = ""
  File = "-"

[[DeviceList]]
  Name = "TemplateDevice"
  Profile = "Example Sensor"
  Description = "An Example Template Device"
  Labels = [ "One", "Two", "Three" ]
  [DeviceList.Protocols]
    [DeviceList.Protocols.Other]
      Address = "someSensorEndpoint"
      Port = 502
  [[DeviceList.AutoEvents]]
    Resource = "SensorOne"
    OnChange = false
    Frequency = "10s"
  [[DeviceList.AutoEvents]]
    Resource = "SensorTwo"
    OnChange = true
    Frequency = "15000ms"
